additional_hostnames:
  - basic
  - umami
hooks:
  post-start:
    - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS basic; GRANT ALL ON basic.* to 'db'@'%';"
      service: db
    - exec: drush @basic.ddev site-install -y --sites-subdir=basic
    - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS umami; GRANT ALL ON umami.* to 'db'@'%';"
      service: db
    - exec: drush @basic.ddev site-install demo_umami -y --sites-subdir=umami
